### ISSUE TITLE
How to spawn entity from handler?

### ISSUE THREAD

**Issue by AskoldMakaruk** [rj00a/evenio#25]

**Comment by jidoc01** [comment]
You can add a new entity through `Insert` event in a system. See https://docs.rs/evenio/latest/evenio/tutorial/ch04_entities_and_components/index.html#bundling-components

**Comment by rj00a** [comment]
You can spawn an entity from a handler by using the [`Sender::spawn`](https://docs.rs/evenio/latest/evenio/event/struct.Sender.html#method.spawn) method.
