### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by jacks0n9** [rj00a/evenio#26]
You probably think you're so clever making the tutorial part of the main code and including markdown for the doc. You're not. It just leads to a worse experience because rustdoc is *not* meant for books. Mdbook is meant for books. Use that with existing markdown files. No one thinks you are smart for some hacky solution for the tutorial (clap does this too for some reason).

**Comment by kalkronline** [comment]
You should open a pull request where you ask if converting to mdbook is something that the author is interested in (or you could just go ahead and do it, it's probably not that much effort). The tone of your issue is really aggressive and weird.

**Comment by rj00a** [comment]
There are good reasons for including the tutorial directly in the rustdoc. But I'm not discussing this with _you_ because of how incredibly rude this comment is. Do better next time.

**Comment by jacks0n9** [comment]
me doing github ban speedrun
