### ISSUE TITLE
Consider removing `Send + Sync` requirements.

### ISSUE THREAD

**Issue by rj00a** [rj00a/evenio#36]
All the data in the `World` currently requires `Send + Sync` bounds. This was done so that #4 could be implemented without a breaking change. However, I'm not sure I want this for a few reasons:

- Performance: Users must use `Arc` and `Mutex` when `Rc` and `RefCell` is sufficient.
- `Send + Sync` bounds make it difficult to work with frameworks like `ggez` and `sdl2` that have `!Send + !Sync` requirements.
- The multithreaded executor as currently implemented in `bevy_ecs` has very significant overhead, to the point where many games can improve their performance by disabling it. This may be sufficient evidence that inter-handler parallelism is not worth implementing.
- Parallel iterators for `Fetcher` may be sufficient for most users.

I would rather not handicap this library indefinitely in order to support a feature which may not actually arrive.

**Comment by spikespaz** [comment]
https://github.com/kuviman/evenio/tree/non-send

**Comment by andrewgazelka** [comment]
I'm all for removing `Send + Sync` and then having a breaking change if needed. :) 

I could benefit from this in https://github.com/andrewgazelka/hyperion

**Comment by andrewgazelka** [comment]
@spikespaz fyi `non-send` needs to compile with `rayon` feature as well
