### ISSUE TITLE
Consider `Deref`/`DerefMut` support for `Single`

### ISSUE THREAD

**Issue by andrewgazelka** [rj00a/evenio#39]
I know `Single` is not a smart pointer, but it effectively acts like one—maybe?

I don't know. I know many people hate `Deref` and `DerefMut` for anything that isn't a smart pointer, but `Single<T>` is just a "pointer" to `T` stored in `evenio`. 

# Related Work
`Json<T>` in axum impls `Deref` and `DerefMut`

https://docs.rs/axum/latest/axum/struct.Json.html

**Comment by rj00a** [comment]
Sounds reasonable. The public `.0` field of `Single` could interfere with deref coercion but other than that it seems fine.
Should do it for `TrySingle` as well for parity.
