### ISSUE TITLE
Add `#[diagnostic]`

### ISSUE THREAD

**Issue by andrewgazelka** [rj00a/evenio#62]
https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html

**Comment by rj00a** [comment]
`#[diagnostic::on_unimplemented]` was already added to `IntoHandler`, but idk where else it would be useful.

**Comment by andrewgazelka** [comment]
> `#[diagnostic::on_unimplemented]` was already added to `IntoHandler`, but idk where else it would be useful.

ah I did not notice this. Let me look and see if I think it would be useful anywhere.
